services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'hotel-resources'
      MYSQL_USER: tripworld
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql:/data/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "5050:8080"
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql:
  adminer:
